#!/usr/bin/env python3
"""Run cmake semantics probes and verify File API output.

Each probe is a small cmake program (generated by probes.exe) with
assertions on the cmake File API JSON output. This empirically verifies
our understanding of cmake's string/target/file semantics.

Usage: python3 test/test_cmake_probes.py [probe_name ...]
  Run from project root. If no names given, runs all probes.
"""

import json, glob, os, shutil, subprocess, sys, tempfile

PROBES_EXE = "_build/default/test/test-cmake-semantics/probes.exe"


# ---- File API helpers (from cmake_file_api_cmp.py) ----

def run_cmake(source_dir, build_dir):
    """Run cmake configure with File API query. Returns (success, stderr)."""
    query = os.path.join(build_dir, ".cmake", "api", "v1", "query")
    os.makedirs(query, exist_ok=True)
    open(os.path.join(query, "codemodel-v2"), "w").close()
    open(os.path.join(query, "cache-v2"), "w").close()
    r = subprocess.run(
        ["cmake", "-S", source_dir, "-B", build_dir],
        capture_output=True, text=True,
    )
    return r.returncode == 0, r.stderr


def strip_unstable(obj):
    """Strip fields that vary between runs."""
    if isinstance(obj, dict):
        return {
            k: strip_unstable(v)
            for k, v in obj.items()
            if k not in ("jsonFile", "backtrace", "backtraceGraph")
        }
    if isinstance(obj, list):
        return [strip_unstable(v) for v in obj]
    return obj


def load_replies(build_dir):
    reply_dir = os.path.join(build_dir, ".cmake", "api", "v1", "reply")
    if not os.path.isdir(reply_dir):
        return {}
    results = {}
    for pattern in ["codemodel-v2", "cache-v2", "target-*"]:
        files = glob.glob(os.path.join(reply_dir, f"{pattern}*.json"))
        for f in files:
            basename = os.path.basename(f)
            key = basename.rsplit("-", 1)[0]
            with open(f) as fh:
                results[key] = strip_unstable(json.load(fh))
    return results


def get_targets(replies):
    """Extract {name: target_json} from File API replies."""
    targets = {}
    for key, val in replies.items():
        if key.startswith("target-"):
            name = val.get("name", key)
            targets[name] = val
    return targets


def get_cache_entries(replies):
    """Extract {name: {type, value}} from cache reply."""
    cache = replies.get("cache-v2", {})
    entries = {}
    for e in cache.get("entries", []):
        entries[e["name"]] = {"type": e.get("type"), "value": e.get("value")}
    return entries


# ---- Probe runner ----

def get_probe_list():
    r = subprocess.run([PROBES_EXE, "--list"], capture_output=True, text=True)
    return r.stdout.strip().split("\n")


def get_probe_cmake(name):
    r = subprocess.run([PROBES_EXE, name], capture_output=True, text=True)
    return r.stdout


def get_probe_sources(name):
    r = subprocess.run([PROBES_EXE, name, "--sources"], capture_output=True, text=True)
    return [s for s in r.stdout.strip().split("\n") if s]


def get_probe_subdirs(name):
    r = subprocess.run([PROBES_EXE, name, "--subdirs"], capture_output=True, text=True)
    return [s for s in r.stdout.strip().split("\n") if s]


def get_probe_subdir_cmake(name, subdir):
    r = subprocess.run([PROBES_EXE, name, "--subdir", subdir], capture_output=True, text=True)
    return r.stdout


def get_probe_subdir_sources(name, subdir):
    r = subprocess.run([PROBES_EXE, name, "--subdir-sources", subdir], capture_output=True, text=True)
    return [s for s in r.stdout.strip().split("\n") if s]


def setup_probe_project(name, tmpdir):
    """Create a cmake project directory for the probe."""
    src = os.path.join(tmpdir, "src")
    os.makedirs(src)

    # Write root CMakeLists.txt
    with open(os.path.join(src, "CMakeLists.txt"), "w") as f:
        f.write(get_probe_cmake(name))

    # Create dummy source files
    for s in get_probe_sources(name):
        path = os.path.join(src, s)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            if s.endswith(".c") or s.endswith(".cxx") or s.endswith(".cpp"):
                f.write("/* dummy */\n")
            elif s.endswith(".h.in"):
                f.write("/* config template */\n")
            else:
                f.write("")

    # Create subdirectories
    for subdir in get_probe_subdirs(name):
        subdir_path = os.path.join(src, subdir)
        os.makedirs(subdir_path, exist_ok=True)
        with open(os.path.join(subdir_path, "CMakeLists.txt"), "w") as f:
            f.write(get_probe_subdir_cmake(name, subdir))
        for s in get_probe_subdir_sources(name, subdir):
            path = os.path.join(subdir_path, s)
            with open(path, "w") as f:
                f.write("/* dummy */\n")

    return src


# ---- Assertions ----

EXPECTATIONS = {
    "target_from_lib": {
        "expect_success": True,
        "targets": {"foo": {"type": "STATIC_LIBRARY"}},
    },
    "target_from_exe": {
        "expect_success": True,
        "targets": {"bar": {"type": "EXECUTABLE"}},
    },
    "target_interface": {
        "expect_success": True,
        "target_count": 0,
        "note": "standalone INTERFACE library (no consumers) does NOT appear in File API codemodel",
    },
    "target_named_like_file": {
        "expect_success": True,
        "targets": {"foo.c": {"type": "STATIC_LIBRARY"}},
        "note": "cmake allows target names that look like filenames",
    },
    "target_interface_with_consumer": {
        "expect_success": True,
        "targets": {
            "app": {"type": "EXECUTABLE"},
        },
        "target_absent": ["iface"],
        "note": "INTERFACE library NEVER appears in File API codemodel — even when consumed",
    },
    "configure_file_no_target": {
        "expect_success": True,
        "target_count": 0,
        "note": "configure_file creates a file, not a target",
    },
    "install_file_no_target": {
        "expect_success": True,
        "target_count": 0,
        "note": "install(FILES) references files without creating targets",
    },
    "same_name_target_and_subdir": {
        "expect_success": True,
        "targets": {"app": {"type": "EXECUTABLE"}, "MathLib": {"type": "STATIC_LIBRARY"}},
        "note": "same string 'Math' used as subdir name and parent of target — no conflict",
    },
    "missing_source_file": {
        "expect_success": False,
        "note": "cmake fails at configure time when source file doesn't exist",
    },
    "target_link_creates_dep": {
        "expect_success": True,
        "targets": {"liba": {"type": "STATIC_LIBRARY"}, "libb": {"type": "STATIC_LIBRARY"}},
        "check_link": ("liba", "libb"),
        "note": "target_link_libraries creates dependency visible in File API",
    },
    "target_with_definitions": {
        "expect_success": True,
        "targets": {"foo": {"type": "STATIC_LIBRARY"}},
        "check_define": ("foo", "USE_X"),
        "note": "target_compile_definitions visible in compileGroups",
    },
    "set_var_not_target": {
        "expect_success": True,
        "target_count": 0,
        "cache_absent": ["FOO"],
        "note": "set() without CACHE creates a normal variable — NOT visible in cache or File API",
    },
    "option_creates_cache": {
        "expect_success": True,
        "target_count": 0,
        "cache_has": {"USE_X": "ON"},
        "cache_type": {"USE_X": "BOOL"},
        "note": "option() creates a BOOL cache entry",
    },
    "two_targets_same_source": {
        "expect_success": True,
        "targets": {"libA": {"type": "STATIC_LIBRARY"}, "libB": {"type": "STATIC_LIBRARY"}},
        "note": "same source file can belong to multiple targets",
    },
    # Category 8: cmake introspection — what kind is a string?
    "string_kind_after_add_library": {
        "expect_success": True,
        "cache_has": {
            "IS_TARGET_foo": "yes",
            "IS_TARGET_foo_c": "no",
            "IS_DEFINED_foo": "no",
        },
        "note": "after add_library(foo foo.c): 'foo' is TARGET, 'foo.c' is NOT target, 'foo' is NOT a variable",
    },
    "string_kind_after_set": {
        "expect_success": True,
        "cache_has": {
            "IS_TARGET_MYVAR": "no",
            "IS_DEFINED_MYVAR": "yes",
        },
        "note": "after set(MYVAR hello): 'MYVAR' is DEFINED but NOT a TARGET",
    },
    "string_kind_interface_is_target": {
        "expect_success": True,
        "cache_has": {
            "IS_TARGET_iface": "yes",
        },
        "note": "INTERFACE library IS a target (if(TARGET) returns true) even though invisible in File API codemodel",
    },
    "string_kind_after_option": {
        "expect_success": True,
        "cache_has": {
            "IS_TARGET_MY_OPT": "no",
            "IS_DEFINED_MY_OPT": "yes",
        },
        "note": "option() creates a DEFINED variable but NOT a target",
    },
    # Category 9: All cmake namespaces
    "ns_command_builtin": {
        "expect_success": True,
        "cache_has": {
            "IS_CMD_add_library": "yes",
            "IS_CMD_set": "yes",
            "IS_CMD_nonexistent": "no",
        },
        "note": "built-in cmake commands live in COMMAND namespace",
    },
    "ns_command_function": {
        "expect_success": True,
        "cache_has": {
            "IS_CMD_my_func": "yes",
            "IS_TARGET_my_func": "no",
            "IS_DEFINED_my_func": "no",
        },
        "note": "function() creates a COMMAND, not a target or variable",
    },
    "ns_test": {
        "expect_success": True,
        "targets": {"runner": {"type": "EXECUTABLE"}},
        "cache_has": {
            "IS_TEST_mytest": "yes",
            "IS_TARGET_mytest": "no",
            "IS_DEFINED_mytest": "no",
            "IS_TARGET_runner": "yes",
        },
        "note": "add_test creates TEST entry; test name != target name, independent namespaces",
    },
    "ns_cache_vs_normal": {
        "expect_success": True,
        "cache_has": {
            "IS_DEFINED_NORMAL": "yes",
            "IS_CACHE_NORMAL": "no",
            "IS_DEFINED_CACHE": "yes",
            "IS_CACHE_CACHE": "yes",
        },
        "note": "set() → DEFINED but not CACHE{}; set(CACHE) → both DEFINED and CACHE{}",
    },
    "ns_overlap_all": {
        "expect_success": True,
        "targets": {"foo": {"type": "STATIC_LIBRARY"}},
        "cache_has": {
            "IS_TARGET_foo": "yes",
            "IS_DEFINED_foo": "yes",
            "IS_CACHE_foo": "yes",
            "IS_CMD_foo": "no",
        },
        "note": "same string 'foo' is simultaneously a TARGET, variable, and CACHE entry — all independent",
    },
    "ns_policy": {
        "expect_success": True,
        "cache_has": {
            "HAS_POLICY_CMP0048": "yes",
            "HAS_POLICY_CMP9999": "no",
        },
        "note": "POLICY namespace: known policies exist, unknown ones don't",
    },
}


def check_probe(name, verbose=False):
    """Run one probe, return (passed, errors)."""
    expect = EXPECTATIONS.get(name)
    if expect is None:
        return False, [f"no expectations defined for '{name}'"]

    errors = []
    with tempfile.TemporaryDirectory(prefix=f"cmake_probe_{name}_") as tmpdir:
        src = setup_probe_project(name, tmpdir)
        build = os.path.join(tmpdir, "build")

        success, stderr = run_cmake(src, build)

        # Check success/failure
        if expect.get("expect_success", True):
            if not success:
                errors.append(f"cmake configure failed (expected success)\n{stderr}")
                return False, errors
        else:
            if success:
                errors.append("cmake configure succeeded (expected failure)")
            return len(errors) == 0, errors

        replies = load_replies(build)
        targets = get_targets(replies)
        cache = get_cache_entries(replies)

        # Check target count
        if "target_count" in expect:
            if len(targets) != expect["target_count"]:
                errors.append(
                    f"target_count: expected {expect['target_count']}, got {len(targets)} "
                    f"({list(targets.keys())})"
                )

        # Check specific targets
        if "targets" in expect:
            for tname, texpect in expect["targets"].items():
                if tname not in targets:
                    errors.append(f"target '{tname}' not found (have: {list(targets.keys())})")
                    continue
                t = targets[tname]
                if "type" in texpect and t.get("type") != texpect["type"]:
                    errors.append(
                        f"target '{tname}' type: expected {texpect['type']}, got {t.get('type')}"
                    )

        # Check targets that should NOT exist
        if "target_absent" in expect:
            for tname in expect["target_absent"]:
                if tname in targets:
                    errors.append(f"target '{tname}' should NOT exist but found")

        # Check link dependency
        if "check_link" in expect:
            from_t, to_t = expect["check_link"]
            if from_t in targets:
                t = targets[from_t]
                deps = []
                for cg in t.get("compileGroups", []):
                    pass
                # Check dependencies field
                found_dep = False
                for dep in t.get("dependencies", []):
                    dep_id = dep.get("id", "")
                    # dependency id format: "target_name::hash"
                    if to_t in dep_id:
                        found_dep = True
                        break
                if not found_dep:
                    errors.append(
                        f"target '{from_t}' should depend on '{to_t}' but dependency not found"
                    )

        # Check compile definition
        if "check_define" in expect:
            tname, define = expect["check_define"]
            if tname in targets:
                t = targets[tname]
                found = False
                for cg in t.get("compileGroups", []):
                    for d in cg.get("defines", []):
                        if d.get("define", "").startswith(define):
                            found = True
                            break
                if not found:
                    errors.append(
                        f"target '{tname}' should have define '{define}' but not found in compileGroups"
                    )

        # Check cache entries
        if "cache_has" in expect:
            for cname, cval in expect["cache_has"].items():
                if cname not in cache:
                    errors.append(f"cache variable '{cname}' not found")
                elif cache[cname]["value"] != cval:
                    errors.append(
                        f"cache '{cname}': expected value '{cval}', got '{cache[cname]['value']}'"
                    )

        # Check cache absent
        if "cache_absent" in expect:
            for cname in expect["cache_absent"]:
                if cname in cache:
                    errors.append(f"cache variable '{cname}' should NOT exist but found")

        if "cache_type" in expect:
            for cname, ctype in expect["cache_type"].items():
                if cname in cache and cache[cname]["type"] != ctype:
                    errors.append(
                        f"cache '{cname}': expected type '{ctype}', got '{cache[cname]['type']}'"
                    )

        if verbose and not errors:
            note = expect.get("note", "")
            if note:
                print(f"    confirmed: {note}")

    return len(errors) == 0, errors


def main():
    # Build probes first
    r = subprocess.run(
        ["dune", "build", "test/test-cmake-semantics/"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print("dune build failed:")
        print(r.stderr)
        sys.exit(2)

    # Get probe list
    if len(sys.argv) > 1:
        probes = sys.argv[1:]
    else:
        probes = get_probe_list()

    passed = 0
    failed = 0
    print("--- cmake semantics probes ---")
    for name in probes:
        ok, errors = check_probe(name, verbose=True)
        if ok:
            print(f"  {name}: PASS")
            passed += 1
        else:
            print(f"  {name}: FAIL")
            for e in errors:
                print(f"    {e}")
            failed += 1

    print(f"\nPassed: {passed}, Failed: {failed}")
    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
