(tests
 (names
  test_yelu_compile
  test_yelu_lexer
  test_yelu_cmake_parse
  test_yelu_lift_lower
  test_yelu_dual_eval
  test_yelu_cache
  test_yelu_steps
  test_yelu_emit_debug
  test_yelu_emit
  test_yelu_function
  test_yelu_foreach
  test_yelu_block_return
  test_yelu_utils_stubs)
 (libraries base alcotest angstrom yelu_langs step_common)
 (preprocess
  (pps ppx_jane)))
